# Generated by Django 5.2.6 on 2025-11-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('web', 'Web Application'), ('mobile', 'Mobile Application'), ('web_mobile', 'Web and Mobile Application'), ('api', 'API/Backend'), ('fullstack', 'Full Stack'), ('devops', 'DevOps/Infrastructure')], max_length=20),
        ),
    ]
